### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by Ayaz223** [UBrainDev/btc-faucet#1]
When I Register Or Login A Blank Screen Appears Saying Webpage Not Working.

**Comment by minter69** [comment]
Go to /public_html/login.php in your File manager and change this line (#85) (add your sitekey)
<div class="h-captcha mb-1 mt-1" data-sitekey="your sitekey"></div>
But there is some problem with creating account in database

**Comment by urbainn** [comment]
Hello,
You might have misconfigured your database credentials, look in the `src/config/pdo.php` and check if the info you have entered is correct.
